/* tslint:disable */
/* eslint-disable */
/**
 * Type declarations for the @crdt-sync/core WASM stub.
 *
 * These types match the interface generated by wasm-bindgen.
 * Replace this file with the real wasm-pack output when building for production.
 */

export class WasmStateStore {
    constructor(node_id: string);
    set_register(key: string, value_json: string): string;
    get_register(key: string): string | undefined;
    apply_envelope(envelope_json: string): void;
}

export type InitInput =
    | RequestInfo
    | URL
    | Response
    | BufferSource
    | WebAssembly.Module;

export default function init(input?: InitInput | Promise<InitInput>): Promise<void>;
